CREATE TABLE `service_request_attachments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`serviceRequestId` int NOT NULL,
	`equipmentId` int,
	`uploadedBy` int,
	`fileName` varchar(255) NOT NULL,
	`contentType` varchar(120) NOT NULL,
	`sizeBytes` int NOT NULL,
	`storageUrl` text NOT NULL,
	`description` varchar(255),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `service_request_attachments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `service_request_comments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`serviceRequestId` int NOT NULL,
	`userId` int NOT NULL,
	`body` text NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `service_request_comments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `service_request_equipment` (
	`id` int AUTO_INCREMENT NOT NULL,
	`serviceRequestId` int NOT NULL,
	`productId` int,
	`equipmentCategory` varchar(160) NOT NULL,
	`manufacturer` varchar(255),
	`model` varchar(180),
	`serialNumber` varchar(180),
	`assetNumber` varchar(180),
	`installationYear` int,
	`lastMaintenanceDate` varchar(40),
	`warrantyStatus` enum('under_warranty','out_of_warranty','unknown') NOT NULL DEFAULT 'unknown',
	`equipmentLocation` varchar(180),
	`roomDepartment` varchar(180),
	`deviceAddress` text,
	`operationalStatus` enum('yes','partially','no','unknown') NOT NULL DEFAULT 'unknown',
	`problemTitle` varchar(255) NOT NULL,
	`problemDescription` text NOT NULL,
	`errorCode` varchar(255),
	`alarmMessage` text,
	`problemStartedAt` varchar(120),
	`occurrencePattern` enum('continuous','intermittent','unknown') NOT NULL DEFAULT 'unknown',
	`precedingEvent` varchar(180),
	`safeToUse` enum('yes','no','unknown') NOT NULL DEFAULT 'unknown',
	`previousMaintenance` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `service_request_equipment_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `service_requests` (
	`id` int AUTO_INCREMENT NOT NULL,
	`publicNumber` varchar(40) NOT NULL,
	`quoteRequestId` int,
	`organizationName` varchar(255),
	`requesterType` enum('doctor','biomedical_engineer','technician','procurement_officer','hospital','clinic','medical_center','distributor','private_company','government_entity','individual','other'),
	`contactPerson` varchar(255) NOT NULL,
	`jobTitle` varchar(180),
	`email` varchar(320) NOT NULL,
	`phone` varchar(80) NOT NULL,
	`whatsapp` varchar(80),
	`preferredContactMethod` enum('email','phone','whatsapp','any') NOT NULL DEFAULT 'any',
	`country` varchar(120) NOT NULL,
	`city` varchar(160),
	`address` text,
	`visitRequired` enum('yes','no','not_sure') NOT NULL DEFAULT 'not_sure',
	`preferredVisitDate` varchar(40),
	`preferredVisitTime` varchar(80),
	`siteAccessNotes` text,
	`safetyAcknowledged` boolean NOT NULL DEFAULT false,
	`noPatientDataAcknowledged` boolean NOT NULL DEFAULT false,
	`status` enum('new','under_review','assigned','waiting_for_customer','remote_diagnosis','site_visit_required','quotation_required','awaiting_approval','scheduled','in_progress','waiting_for_parts','resolved','customer_confirmation','closed','cancelled') NOT NULL DEFAULT 'new',
	`priority` enum('low','normal','high','urgent') NOT NULL DEFAULT 'normal',
	`assignedServiceUserId` int,
	`assignedSalesUserId` int,
	`source` enum('website','product_page','service_page','whatsapp','email','manual','campaign') NOT NULL DEFAULT 'website',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`closedAt` timestamp,
	CONSTRAINT `service_requests_id` PRIMARY KEY(`id`),
	CONSTRAINT `service_requests_publicNumber_unique` UNIQUE(`publicNumber`)
);
