CREATE TABLE `cms_media_assets` (
	`id` int AUTO_INCREMENT NOT NULL,
	`fileKey` varchar(500) NOT NULL,
	`storageUrl` text NOT NULL,
	`fileName` varchar(255) NOT NULL,
	`contentType` varchar(120) NOT NULL,
	`sizeBytes` int NOT NULL,
	`assetType` enum('website_image','product_image','service_image','certificate','ce_document','quality_document','agency_letter','customer_letter','brochure','technical_file','other') NOT NULL DEFAULT 'other',
	`altText` varchar(500) NOT NULL DEFAULT '',
	`caption` varchar(500) NOT NULL DEFAULT '',
	`description` text,
	`visibility` enum('public','internal') NOT NULL DEFAULT 'internal',
	`isTemporary` boolean NOT NULL DEFAULT false,
	`workflowStatus` enum('draft','pending_review','approved','published','archived') NOT NULL DEFAULT 'draft',
	`linkedPageSlug` varchar(180),
	`uploadedBy` int,
	`reviewedBy` int,
	`publishedBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`reviewedAt` timestamp,
	`publishedAt` timestamp,
	`archivedAt` timestamp,
	CONSTRAINT `cms_media_assets_id` PRIMARY KEY(`id`),
	CONSTRAINT `cms_media_assets_fileKey_unique` UNIQUE(`fileKey`)
);
--> statement-breakpoint
CREATE TABLE `cms_pages` (
	`id` int AUTO_INCREMENT NOT NULL,
	`slug` varchar(180) NOT NULL,
	`pageType` enum('about','maintenance_contracts','faqs','downloads','news','events','careers','spare_parts','resources','contact','privacy','terms') NOT NULL,
	`draftData` text NOT NULL,
	`publishedData` text NOT NULL,
	`draftVisible` boolean NOT NULL DEFAULT true,
	`publishedVisible` boolean NOT NULL DEFAULT true,
	`workflowStatus` enum('draft','pending_review','approved','published','archived') NOT NULL DEFAULT 'draft',
	`requiresQaReview` boolean NOT NULL DEFAULT false,
	`createdBy` int,
	`updatedBy` int,
	`reviewedBy` int,
	`publishedBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`reviewedAt` timestamp,
	`publishedAt` timestamp,
	`archivedAt` timestamp,
	CONSTRAINT `cms_pages_id` PRIMARY KEY(`id`),
	CONSTRAINT `cms_pages_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `site_stats` (
	`id` int AUTO_INCREMENT NOT NULL,
	`metricKey` varchar(120) NOT NULL,
	`draftValue` varchar(120) NOT NULL,
	`publishedValue` varchar(120) NOT NULL,
	`draftLabel` varchar(255) NOT NULL,
	`publishedLabel` varchar(255) NOT NULL,
	`draftDescription` text,
	`publishedDescription` text,
	`draftVisible` boolean NOT NULL DEFAULT true,
	`publishedVisible` boolean NOT NULL DEFAULT true,
	`displayOrder` int NOT NULL DEFAULT 0,
	`updatedBy` int,
	`publishedBy` int,
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`publishedAt` timestamp,
	CONSTRAINT `site_stats_id` PRIMARY KEY(`id`),
	CONSTRAINT `site_stats_metricKey_unique` UNIQUE(`metricKey`)
);
