import { Filter, PackageSearch, ArrowUpRight } from "lucide-react";
import { Link } from "wouter";
import { useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { trpc } from "@/lib/trpc";

const labels: Record<string, string> = { medical_device: "Medical device", spare_part: "Spare part", accessory: "Accessory", available: "Available", on_request: "On request", coming_soon: "Coming soon", discontinued: "Discontinued" };
export default function Catalogue() {
  const query = trpc.products.published.useQuery();
  const [type, setType] = useState("all");
  const products = useMemo(() => (query.data ?? []).filter(item => type === "all" || item.productType === type), [query.data, type]);
  return <main className="min-h-screen bg-[#f5f7fb] text-slate-950"><header className="border-b bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-5"><Link href="/" className="font-semibold tracking-tight">SPM <span className="ml-2 text-xs font-normal uppercase tracking-[0.2em] text-slate-500">Catalogue</span></Link><Link href="/"><Button variant="outline">Back to website</Button></Link></div></header><section className="mx-auto max-w-7xl px-6 py-16"><div className="flex flex-col gap-6 md:flex-row md:items-end md:justify-between"><div><p className="text-sm font-semibold uppercase tracking-[0.25em] text-cyan-700">Medical imaging portfolio</p><h1 className="mt-3 text-5xl font-semibold tracking-tight">Products and equipment</h1><p className="mt-4 max-w-2xl text-lg leading-8 text-slate-600">Browse the published SPM catalogue. Product details, documents and quote requests are controlled by the SPM team.</p></div><div className="flex items-center gap-2"><Filter className="h-4 w-4 text-slate-500" /><Select value={type} onValueChange={setType}><SelectTrigger className="w-52 bg-white"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All product types</SelectItem><SelectItem value="medical_device">Medical devices</SelectItem><SelectItem value="spare_part">Spare parts</SelectItem><SelectItem value="accessory">Accessories</SelectItem></SelectContent></Select></div></div><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{products.map(item => { const data = item.data as Record<string, any>; return <Card key={item.id} className="group overflow-hidden border-0 shadow-sm"><div className="aspect-[4/3] bg-slate-100">{data.mainImage ? <img src={data.mainImage} alt={data.name || item.slug} className="h-full w-full object-cover transition duration-300 group-hover:scale-105" /> : <div className="flex h-full items-center justify-center text-slate-400"><PackageSearch className="h-12 w-12" /></div>}</div><CardContent className="space-y-4 p-6"><div className="flex items-center justify-between gap-2"><Badge variant="outline">{labels[item.productType]}</Badge>{data.featured ? <Badge className="bg-cyan-700">Featured</Badge> : null}</div><div><h2 className="text-xl font-semibold">{data.name}</h2><p className="mt-1 text-sm text-slate-500">{[data.brand, data.modelNumber].filter(Boolean).join(" · ")}</p></div><p className="line-clamp-3 leading-7 text-slate-600">{data.shortDescription || data.fullDescription}</p><Link href={`/catalogue/${item.slug}`}><Button className="w-full" variant="outline">View product <ArrowUpRight className="ml-2 h-4 w-4" /></Button></Link></CardContent></Card>; })}</div>{!query.isLoading && products.length === 0 ? <div className="mt-12 rounded-3xl border border-dashed bg-white p-14 text-center text-slate-500">No published products in this category yet.</div> : null}</section></main>;
}
