import { ArrowUpRight, BookOpen, BriefcaseBusiness, CalendarDays, Download, FileQuestion, Handshake, Mail, Newspaper, ShieldCheck, Boxes } from "lucide-react";
import { Link, useRoute } from "wouter";
import SiteChrome from "@/components/SiteChrome";
import { trpc } from "@/lib/trpc";

type PageConfig = { eyebrow: string; title: string; intro: string; icon: typeof Download; cards: { title: string; text: string; href?: string }[] };

const pages: Record<string, PageConfig> = {
  "/spare-parts": { eyebrow: "SPARE PARTS", title: "The right part starts with the right equipment context.", intro: "Share the part information, equipment details and evidence available to your team. SPM will review the request and guide the next step.", icon: Boxes, cards: [{ title: "Identify the equipment", text: "Manufacturer, model, serial number and asset context help the review start with useful detail." }, { title: "Share evidence", text: "Add a nameplate image, part image, report or video when it helps explain the need." }, { title: "Request a part", text: "Use the structured intake to request a listed part or a custom item not yet in the catalogue." }] },
  "/resources": { eyebrow: "RESOURCE CENTER", title: "Practical information for equipment teams.", intro: "A central place for SPM downloads, FAQs, technical insight, events and reviewed company updates.", icon: BookOpen, cards: [{ title: "Browse downloads", text: "Find approved brochures, guides and technical resources." }, { title: "Read the FAQs", text: "Get concise answers before starting a request." }, { title: "Stay updated", text: "Follow SPM news and events as they are approved for publication." }] },
  "/contact": { eyebrow: "CONTACT SPM", title: "Tell us what needs to move forward.", intro: "Contact SPM for equipment, service, spare-parts and general business enquiries. Structured requests are available when you are ready to share more context.", icon: Mail, cards: [{ title: "General enquiries", text: "Email info@spmhospitals.com or call +20 12 21888395." }, { title: "Service support", text: "Start a service request and include equipment and fault information." }, { title: "Commercial requests", text: "Request a quote for one or more products, services or custom needs." }] },
  "/privacy": { eyebrow: "PRIVACY", title: "Information handled with purpose.", intro: "The final SPM privacy policy will be reviewed and approved before production publication. This page is a controlled content structure for that policy.", icon: ShieldCheck, cards: [{ title: "What we collect", text: "Only the information needed to respond to a request or operate the internal platform." }, { title: "How it is used", text: "Request and contact data is routed to the responsible SPM team." }, { title: "Your questions", text: "Contact SPM if you need clarification about information handling." }] },
  "/terms": { eyebrow: "TERMS OF USE", title: "Clear terms for using the SPM website.", intro: "The final SPM terms of use will be reviewed and approved before production publication. This page is a controlled content structure for those terms.", icon: ShieldCheck, cards: [{ title: "Website information", text: "Product and service information is subject to internal review and availability." }, { title: "Requests", text: "Submitting a request does not itself create a contract or service commitment." }, { title: "Questions", text: "Contact SPM for clarification before relying on published information." }] },
  "/maintenance-contracts": { eyebrow: "SERVICE CONTINUITY", title: "Maintenance contracts built around your equipment reality.", intro: "A structured place for SPM maintenance coverage, response expectations and support options. Commercial details remain controlled content for SPM review.", icon: Handshake, cards: [{ title: "Preventive maintenance", text: "Keep planned inspections, calibration and service activities visible in one support path." }, { title: "Corrective support", text: "Create a clear route from equipment problem to triage, visit and resolution." }, { title: "Coverage conversations", text: "Share your equipment context so the SPM team can shape the right support scope." }] },
  "/faqs": { eyebrow: "HELP CENTER", title: "Answers before the next technical step.", intro: "A focused FAQ library for equipment, service, parts, requests and documentation. Questions and answers will be managed by authorized SPM users.", icon: FileQuestion, cards: [{ title: "Equipment questions", text: "How to start a product conversation, request a specification or ask for a quote." }, { title: "Service questions", text: "What information helps the Service team understand a maintenance need." }, { title: "Request questions", text: "How references, attachments and internal follow-up work after submission." }] },
  "/downloads": { eyebrow: "DOCUMENT CENTER", title: "Documents with a clear owner and review status.", intro: "Browse approved brochures, technical documents, certificates and controlled resources. Official documents are published only after the relevant internal review.", icon: Download, cards: [{ title: "Product brochures", text: "Product material and technical information managed from the SPM platform." }, { title: "Service resources", text: "Guides and support material prepared for healthcare equipment teams." }, { title: "Quality and regulatory", text: "Evidence-aware documents reviewed by the responsible QA/RA users." }] },
  "/news": { eyebrow: "SPM UPDATES", title: "What is changing across equipment and service.", intro: "A future-ready newsroom for SPM announcements, product updates, service knowledge and company news.", icon: Newspaper, cards: [{ title: "Company updates", text: "Approved announcements and business milestones." }, { title: "Technical insight", text: "Useful educational content for equipment and maintenance teams." }, { title: "Partner updates", text: "Controlled updates about manufacturers, suppliers and partnerships." }] },
  "/events": { eyebrow: "EVENTS", title: "Meet SPM where the conversation happens.", intro: "A structured events area for exhibitions, training sessions, technical meetings and healthcare industry activities.", icon: CalendarDays, cards: [{ title: "Upcoming events", text: "Event details, dates and registration links managed by the content team." }, { title: "Training and workshops", text: "Technical learning moments for the teams who keep equipment moving." }, { title: "Past events", text: "A reviewed archive of SPM participation and approved event material." }] },
  "/careers": { eyebrow: "CAREERS", title: "Build the next layer of medical imaging support.", intro: "A future-ready careers page for engineering, service, commercial, quality and operations opportunities at SPM.", icon: BriefcaseBusiness, cards: [{ title: "Engineering and service", text: "Roles for people who understand equipment, diagnostics and field support." }, { title: "Commercial and operations", text: "Roles that connect customer needs with a reliable internal workflow." }, { title: "Quality and regulatory", text: "Roles that help keep evidence, documentation and claims under control." }] },
  "/about": { eyebrow: "ABOUT SPM", title: "Medical imaging technology with a practical next step.", intro: "SPM supports healthcare organizations and technical teams with equipment, service, parts and structured request journeys. Official company content will be completed and reviewed by SPM.", icon: ShieldCheck, cards: [{ title: "What we support", text: "Equipment sourcing, service coordination, parts requests and technical conversations." }, { title: "How we work", text: "Clear information, responsible ownership and a workflow that keeps the next step visible." }, { title: "Quality-aware communication", text: "Regulatory and quality claims remain subject to the responsible internal review." }] },
};

export default function ContentLanding() {
  const [matched, params] = useRoute("/:slug");
  const path = matched ? `/${params?.slug}` : "/about";
  const fallbackPage = pages[path] ?? pages["/about"];
  const cms = trpc.cms.publishedBySlug.useQuery({ slug: path.slice(1) });
  const page = { ...fallbackPage, ...(cms.data?.data ?? {}) } as PageConfig;
  const Icon = fallbackPage.icon;
  return <SiteChrome><main><section className="bg-[#eaf4fa]"><div className="mx-auto max-w-[1240px] px-5 py-20 lg:px-8 lg:py-28"><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#0f6fae]">{page.eyebrow}</p><h1 className="mt-5 text-5xl font-semibold leading-tight tracking-[-.04em] text-[#0a4052] sm:text-6xl">{page.title}</h1><p className="mt-6 text-lg leading-8 text-[#617180]">{page.intro}</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/request-a-quote" className="inline-flex h-12 items-center rounded-md bg-[#c2410c] px-5 text-sm font-semibold text-white">Request a Quote <ArrowUpRight className="ml-2 h-4 w-4" /></Link><Link href="/contact" className="inline-flex h-12 items-center rounded-md border border-[#0f6fae] px-5 text-sm font-semibold text-[#0f6fae]">Contact SPM</Link></div></div></div></section><section className="mx-auto max-w-[1240px] px-5 py-20 lg:px-8 lg:py-24"><div className="mb-10 flex items-center gap-4"><div className="rounded-2xl bg-[#0a4052] p-4 text-[#8be0d5]"><Icon className="h-7 w-7" /></div><div><p className="text-sm font-semibold text-[#0a4052]">SPM content area</p><p className="text-sm text-[#617180]">Managed by authorized users and reviewed before publication.</p></div></div><div className="grid gap-6 md:grid-cols-3">{page.cards.map(card => <article key={card.title} className="rounded-2xl border border-[#d7e0e7] bg-white p-7 shadow-[0_2px_8px_rgba(11,41,66,.08)]"><h2 className="text-xl font-semibold text-[#0a4052]">{card.title}</h2><p className="mt-3 text-sm leading-7 text-[#617180]">{card.text}</p><Link href={card.href ?? "/contact"} className="mt-6 inline-flex items-center text-sm font-semibold text-[#c2410c]">Ask SPM <ArrowUpRight className="ml-2 h-4 w-4" /></Link></article>)}</div><div className="mt-12 rounded-2xl border border-dashed border-[#bcdde2] bg-[#f7fafc] p-6 text-sm text-[#617180]"><BookOpen className="mb-3 h-5 w-5 text-[#0f6fae]" /><p><strong className="text-[#0a4052]">Content status:</strong> This page structure is ready for SPM-approved content, images and documents to be added from the Owner-controlled content workflow.</p></div></section></main></SiteChrome>;
}
