import { ArrowRight, ArrowUpRight, BadgeCheck, Boxes, Building2, CheckCircle2, ClipboardList, Globe2, HeartHandshake, ShieldCheck, Wrench } from "lucide-react";
import { Link } from "wouter";
import { Button } from "@/components/ui/button";
import SiteChrome from "@/components/SiteChrome";
import { trpc } from "@/lib/trpc";

const fallback: Record<string, string> = {
  "brand.name": "SPM",
  "brand.eyebrow": "SYSTEMS FOR PROJECTS & MAINTENANCE",
  "hero.eyebrow": "MEDICAL IMAGING TECHNOLOGY",
  "hero.title": "Keep critical imaging systems moving.",
  "hero.description": "SPM helps hospitals, clinics, engineers and healthcare teams source equipment, access service support and move from a technical need to a clear next step.",
  "hero.image": "/manus-storage/spm-hero-medical-engineer_fd2460bc.jpg",
};

const solutions = [
  { icon: Wrench, eyebrow: "Service", title: "Practical support for equipment that cannot wait.", text: "From corrective and preventive maintenance to installation, calibration and technical support.", href: "/services", image: "/manus-storage/spm-service-engineer_96348b80.jpg", cta: "Explore services" },
  { icon: Boxes, eyebrow: "Equipment", title: "The right imaging system for the job.", text: "Explore a controlled catalogue of medical imaging equipment, technical specifications and supporting documents.", href: "/catalogue", image: "/manus-storage/spm-equipment-carm_d9a563ca.jpg", cta: "Browse equipment" },
  { icon: ClipboardList, eyebrow: "Spare parts", title: "Parts support that starts with the details.", text: "Share the equipment context, part information and evidence your team has so SPM can review the need accurately.", href: "/spare-parts", image: "/manus-storage/spm-parts-lab_656efe60.jpg", cta: "Request a part" },
];

export default function Home() {
  const query = trpc.homepage.published.useQuery();
  const content = { ...fallback, ...(query.data ?? []).reduce<Record<string, string>>((acc, item) => { acc[item.contentKey] = item.isVisible ? item.publishedValue : ""; return acc; }, {}) };
  return <SiteChrome><main>
    <section className="relative overflow-hidden bg-[#f7fafc]"><div className="mx-auto grid max-w-[1240px] gap-12 px-5 py-14 sm:py-20 lg:grid-cols-[.92fr_1.08fr] lg:items-center lg:px-8 lg:py-24"><div className="relative z-10"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-[#bcdde2] bg-white px-3 py-1.5 text-xs font-bold uppercase tracking-[.16em] text-[#0f6fae]"><span className="h-2 w-2 rounded-full bg-[#60c1bb]" />{content["hero.eyebrow"]}</div><h1 className="max-w-2xl text-5xl font-semibold leading-[1.04] tracking-[-.04em] text-[#0a4052] sm:text-6xl lg:text-[72px]">{content["hero.title"]}</h1><p className="mt-7 max-w-xl text-lg leading-8 text-[#617180]">{content["hero.description"]}</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/request-a-quote"><Button size="lg" className="h-12 rounded-md bg-[#f36b21] px-6 text-white shadow-lg shadow-[#f36b21]/20 hover:bg-[#d95316]">Request a Quote <ArrowUpRight className="ml-2 h-4 w-4" /></Button></Link><Link href="/request-service"><Button size="lg" variant="outline" className="h-12 rounded-md border-[#0f6fae] px-6 text-[#0f6fae] hover:bg-[#eaf4fa]">Request Service <ArrowRight className="ml-2 h-4 w-4" /></Button></Link></div><div className="mt-10 flex flex-wrap gap-x-8 gap-y-3 text-sm text-[#617180]"><span className="inline-flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-[#1e8ac4]" />Structured request journeys</span><span className="inline-flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-[#1e8ac4]" />Controlled content</span></div></div><div className="relative min-h-[420px] overflow-hidden rounded-[28px] bg-[#0a4052] shadow-2xl shadow-[#0a4052]/15 lg:min-h-[560px]"><img src={content["hero.image"] || fallback["hero.image"]} alt="Biomedical engineer inspecting medical imaging equipment" className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-br from-[#0a4052]/15 via-transparent to-[#0a4052]/80" /><div className="absolute bottom-0 left-0 right-0 p-6 sm:p-8"><div className="max-w-md rounded-2xl border border-white/20 bg-[#0a4052]/75 p-5 text-white backdrop-blur-md"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#8be0d5]">A clear operational start</p><p className="mt-2 text-2xl font-semibold leading-tight">From equipment context to the right SPM team.</p><p className="mt-3 text-sm leading-6 text-white/75">Send a request, add the evidence you have and let the workflow keep the next step visible.</p></div></div></div></div></section>
    <section className="border-y border-[#dce7eb] bg-white"><div className="mx-auto grid max-w-[1240px] gap-8 px-5 py-8 sm:grid-cols-3 lg:px-8"><div className="flex items-center gap-4"><div className="rounded-xl bg-[#eaf4fa] p-3 text-[#0f6fae]"><Building2 className="h-6 w-6" /></div><div><p className="text-3xl font-semibold text-[#0a4052]">450</p><p className="text-sm text-[#617180]">Hospitals reached</p></div></div><div className="flex items-center gap-4"><div className="rounded-xl bg-[#eaf4fa] p-3 text-[#0f6fae]"><Globe2 className="h-6 w-6" /></div><div><p className="text-3xl font-semibold text-[#0a4052]">66</p><p className="text-sm text-[#617180]">UPA projects</p></div></div><div className="flex items-center gap-4"><div className="rounded-xl bg-[#fff1e9] p-3 text-[#d95316]"><HeartHandshake className="h-6 w-6" /></div><div><p className="text-sm font-semibold text-[#0a4052]">Built for review</p><p className="text-sm text-[#617180]">Evidence-aware content workflows</p></div></div></div></section>
    <section className="mx-auto max-w-[1240px] px-5 py-20 lg:px-8 lg:py-28"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#0f6fae]">What SPM brings together</p><h2 className="mt-4 max-w-2xl text-4xl font-semibold leading-tight tracking-[-.03em] text-[#0a4052] sm:text-5xl">A connected way to handle equipment, service and parts.</h2></div><Link href="/about" className="inline-flex shrink-0 items-center text-sm font-semibold text-[#0f6fae]">Why SPM <ArrowUpRight className="ml-2 h-4 w-4" /></Link></div><div className="mt-12 grid gap-6 lg:grid-cols-3">{solutions.map(item => <article key={item.title} className="group overflow-hidden rounded-2xl border border-[#d7e0e7] bg-white shadow-[0_2px_8px_rgba(11,41,66,.08)] transition hover:-translate-y-1 hover:shadow-[0_12px_28px_rgba(11,41,66,.12)]"><div className="relative h-56 overflow-hidden"><img src={item.image} alt="" className="h-full w-full object-cover transition duration-500 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-[#0a4052]/60 to-transparent" /><div className="absolute bottom-4 left-4 rounded-xl bg-white/95 p-3 text-[#0f6fae]"><item.icon className="h-5 w-5" /></div></div><div className="p-6"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#0f6fae]">{item.eyebrow}</p><h3 className="mt-3 text-2xl font-semibold leading-tight text-[#0a4052]">{item.title}</h3><p className="mt-3 text-sm leading-7 text-[#617180]">{item.text}</p><Link href={item.href} className="mt-6 inline-flex items-center text-sm font-semibold text-[#d95316]">{item.cta}<ArrowUpRight className="ml-2 h-4 w-4" /></Link></div></article>)}</div></section>
    <section className="bg-[#eaf4fa]"><div className="mx-auto grid max-w-[1240px] gap-10 px-5 py-20 lg:grid-cols-[.8fr_1.2fr] lg:items-center lg:px-8 lg:py-24"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#0f6fae]">A stronger operating rhythm</p><h2 className="mt-4 text-4xl font-semibold leading-tight tracking-[-.03em] text-[#0a4052]">Make the technical next step easier to see.</h2><p className="mt-5 max-w-lg leading-8 text-[#617180]">Every public journey is designed to collect useful context, route the request and keep the responsible team in view.</p><Link href="/request-service"><Button className="mt-8 bg-[#0a4052] text-white hover:bg-[#063545]">Start a Service Request <ArrowUpRight className="ml-2 h-4 w-4" /></Button></Link></div><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-2xl bg-white p-6 shadow-sm"><ShieldCheck className="h-7 w-7 text-[#0f6fae]" /><h3 className="mt-5 text-lg font-semibold text-[#0a4052]">Controlled information</h3><p className="mt-2 text-sm leading-7 text-[#617180]">Content, evidence and publication can move through the right internal review.</p></div><div className="rounded-2xl bg-[#0a4052] p-6 text-white shadow-xl"><BadgeCheck className="h-7 w-7 text-[#60c1bb]" /><h3 className="mt-5 text-lg font-semibold">A clear request path</h3><p className="mt-2 text-sm leading-7 text-white/70">A quote, service or part request starts with the information your team needs.</p></div></div></div></section>
    <section className="mx-auto max-w-[1240px] px-5 py-20 text-center lg:px-8 lg:py-24"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#0f6fae]">Ready when you are</p><h2 className="mx-auto mt-4 max-w-3xl text-4xl font-semibold tracking-[-.03em] text-[#0a4052] sm:text-5xl">Tell SPM what needs to move forward.</h2><p className="mx-auto mt-5 max-w-2xl leading-8 text-[#617180]">Choose the path that matches your need. You can add equipment details, files and context along the way.</p><div className="mt-8 flex flex-wrap justify-center gap-3"><Link href="/request-a-quote"><Button size="lg" className="bg-[#f36b21] text-white hover:bg-[#d95316]">Request a Quote <ArrowUpRight className="ml-2 h-4 w-4" /></Button></Link><Link href="/request-service"><Button size="lg" variant="outline" className="border-[#0f6fae] text-[#0f6fae]">Request Service <ArrowUpRight className="ml-2 h-4 w-4" /></Button></Link></div></section>
  </main></SiteChrome>;
}
