import { ArrowUpRight, Filter, Headphones, Wrench } from "lucide-react";
import { Link } from "wouter";
import { useMemo, useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { trpc } from "@/lib/trpc";

const labels: Record<string, string> = { installation: "Installation", commissioning: "Commissioning", preventive_maintenance: "Preventive maintenance", corrective_maintenance: "Corrective maintenance", emergency_maintenance: "Emergency maintenance", calibration: "Calibration", technical_support: "Technical support", training: "Training", spare_parts_supply: "Spare parts supply", maintenance_contract: "Maintenance contract" };
export default function Services() {
  const query = trpc.services.published.useQuery(); const [type, setType] = useState("all"); const services = useMemo(() => (query.data ?? []).filter(item => type === "all" || item.serviceType === type), [query.data, type]);
  return <main className="min-h-screen bg-[#f5f7fb] text-slate-950"><header className="border-b bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-5"><Link href="/" className="font-semibold tracking-tight">SPM <span className="ml-2 text-xs font-normal uppercase tracking-[0.2em] text-slate-500">Services</span></Link><Link href="/"><Button variant="outline">Back to website</Button></Link></div></header><section className="mx-auto max-w-7xl px-6 py-16"><div className="flex flex-col gap-6 md:flex-row md:items-end md:justify-between"><div><p className="text-sm font-semibold uppercase tracking-[0.25em] text-cyan-700">Service and maintenance</p><h1 className="mt-3 text-5xl font-semibold tracking-tight">Support that stays close to the equipment</h1><p className="mt-4 max-w-2xl text-lg leading-8 text-slate-600">Installation, maintenance, technical support and service programmes prepared for medical imaging operations.</p></div><div className="flex items-center gap-2"><Filter className="h-4 w-4 text-slate-500" /><Select value={type} onValueChange={setType}><SelectTrigger className="w-60 bg-white"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All service types</SelectItem>{Object.entries(labels).map(([value, label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></div></div><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{services.map(item => { const data = item.data as Record<string, any>; return <Card key={item.id} className="group overflow-hidden border-0 shadow-sm"><div className="aspect-[4/3] bg-slate-100">{data.mainImage ? <img src={data.mainImage} alt={data.name || item.slug} className="h-full w-full object-cover transition duration-300 group-hover:scale-105" /> : <div className="flex h-full items-center justify-center text-slate-400"><Wrench className="h-12 w-12" /></div>}</div><CardContent className="space-y-4 p-6"><Badge variant="outline">{labels[item.serviceType]}</Badge><div><h2 className="text-xl font-semibold">{data.name}</h2><p className="mt-3 line-clamp-3 leading-7 text-slate-600">{data.shortDescription || data.fullDescription}</p></div><Link href={`/services/${item.slug}`}><Button className="w-full" variant="outline">View service <ArrowUpRight className="ml-2 h-4 w-4" /></Button></Link></CardContent></Card>; })}</div>{!query.isLoading && services.length === 0 ? <div className="mt-12 rounded-3xl border border-dashed bg-white p-14 text-center text-slate-500">No published services in this category yet.</div> : null}</section></main>;
}
