import { useState } from "react";
import { ChevronDown, Menu, X, ArrowUpRight, Mail, PhoneCall } from "lucide-react";
import { Link } from "wouter";
import { Button } from "@/components/ui/button";

const logo = "/manus-storage/spm-logo-cropped_7b519adc.webp";

const nav = [
  { label: "Services", href: "/services", children: ["All Services", "Request Service", "Maintenance Contracts"] },
  { label: "Equipment", href: "/catalogue", children: ["Browse Equipment", "Product Catalogue", "Request a Quote"] },
  { label: "Spare Parts", href: "/spare-parts", children: ["Parts Overview", "Request a Part"] },
  { label: "Resources", href: "/resources", children: ["Downloads", "FAQs", "News", "Events"] },
  { label: "Company", href: "/about", children: ["About SPM", "Careers", "Contact Us"] },
];

export default function SiteChrome({ children }: { children: React.ReactNode }) {
  const [open, setOpen] = useState(false);
  return <div className="min-h-screen bg-[#f7fafc] text-[#17212b]">
    <div className="bg-[#0a4052] px-5 py-2 text-xs text-white/90"><div className="mx-auto flex max-w-[1240px] items-center justify-between gap-4"><div className="flex items-center gap-4"><a href="tel:+201221888395" className="inline-flex items-center gap-1.5"><PhoneCall className="h-3.5 w-3.5 text-[#60c1bb]" /> +20 12 21888395</a><span className="hidden text-white/50 sm:inline">Medical imaging technology</span></div><a href="mailto:info@spmhospitals.com" className="hidden items-center gap-1.5 sm:inline-flex"><Mail className="h-3.5 w-3.5 text-[#60c1bb]" /> info@spmhospitals.com</a></div></div>
    <header className="sticky top-0 z-40 border-b border-[#dce7eb]/80 bg-white/95 backdrop-blur"><div className="mx-auto flex h-[76px] max-w-[1240px] items-center justify-between gap-6 px-5 lg:px-8"><Link href="/" className="flex shrink-0 items-center gap-3" onClick={() => setOpen(false)}><img src={logo} alt="SPM Medical Imaging Technology" className="h-12 w-auto object-contain" /><span className="sr-only">SPM</span></Link><nav className="hidden items-center gap-1 lg:flex">{nav.map(item => <div key={item.label} className="group relative"><Link href={item.href} className="inline-flex items-center gap-1 rounded-md px-3 py-5 text-sm font-medium text-[#394957] transition hover:text-[#0f6fae]">{item.label}<ChevronDown className="h-3.5 w-3.5 text-[#7b8c98]" /></Link><div className="pointer-events-none absolute left-0 top-full w-60 translate-y-2 rounded-xl border border-[#d7e0e7] bg-white p-2 opacity-0 shadow-xl transition group-hover:pointer-events-auto group-hover:translate-y-0 group-hover:opacity-100">{item.children.map(child => <Link key={child} href={child === "Request Service" ? "/request-service" : child === "Request a Quote" ? "/request-a-quote" : item.href} className="flex items-center justify-between rounded-lg px-3 py-2.5 text-sm text-[#394957] hover:bg-[#eaf4fa] hover:text-[#0f6fae]">{child}<ArrowUpRight className="h-3.5 w-3.5" /></Link>)}</div></div>)}</nav><div className="hidden items-center gap-3 lg:flex"><Link href="/request-a-quote"><Button className="h-11 rounded-md bg-[#f36b21] px-5 text-sm font-semibold text-white shadow-sm hover:bg-[#d95316]">Request a Quote <ArrowUpRight className="ml-2 h-4 w-4" /></Button></Link></div><button className="rounded-md border border-[#d7e0e7] p-2 lg:hidden" onClick={() => setOpen(value => !value)} aria-label={open ? "Close menu" : "Open menu"}>{open ? <X className="h-5 w-5" /> : <Menu className="h-5 w-5" />}</button></div>{open ? <div className="border-t border-[#d7e0e7] bg-white px-5 py-4 lg:hidden">{nav.map(item => <div key={item.label} className="border-b border-[#eef3f5] py-3 last:border-0"><Link href={item.href} onClick={() => setOpen(false)} className="block text-sm font-semibold text-[#0a4052]">{item.label}</Link><div className="mt-2 grid gap-2 pl-3">{item.children.map(child => <Link key={child} href={child === "Request Service" ? "/request-service" : child === "Request a Quote" ? "/request-a-quote" : item.href} onClick={() => setOpen(false)} className="text-sm text-[#617180]">{child}</Link>)}</div></div>)}<Link href="/request-a-quote" onClick={() => setOpen(false)}><Button className="mt-4 w-full bg-[#f36b21] text-white hover:bg-[#d95316]">Request a Quote</Button></Link></div> : null}</header>
    {children}
    <footer className="bg-[#0a4052] text-white"><div className="mx-auto grid max-w-[1240px] gap-12 px-5 py-16 lg:grid-cols-[1.25fr_.8fr_.8fr_1fr] lg:px-8"><div><div className="mb-5 inline-flex rounded-lg bg-white p-2"><img src={logo} alt="SPM" className="h-12 w-auto object-contain" /></div><p className="max-w-sm text-sm leading-7 text-white/70">Medical imaging technology, service and support built around reliable equipment and clear next steps.</p><Link href="/contact" className="mt-6 inline-flex items-center text-sm font-semibold text-[#60c1bb]">Talk to SPM <ArrowUpRight className="ml-2 h-4 w-4" /></Link></div><div><p className="mb-4 text-xs font-bold uppercase tracking-[.18em] text-[#60c1bb]">Solutions</p><div className="grid gap-3 text-sm text-white/70"><Link href="/catalogue">Equipment</Link><Link href="/services">Services</Link><Link href="/spare-parts">Spare Parts</Link><Link href="/maintenance-contracts">Maintenance Contracts</Link></div></div><div><p className="mb-4 text-xs font-bold uppercase tracking-[.18em] text-[#60c1bb]">Resources</p><div className="grid gap-3 text-sm text-white/70"><Link href="/downloads">Downloads</Link><Link href="/faqs">FAQs</Link><Link href="/news">News</Link><Link href="/events">Events</Link><Link href="/careers">Careers</Link></div></div><div><p className="mb-4 text-xs font-bold uppercase tracking-[.18em] text-[#60c1bb]">Contact</p><div className="grid gap-3 text-sm text-white/70"><a href="mailto:info@spmhospitals.com">info@spmhospitals.com</a><a href="tel:+201221888395">+20 12 21888395</a><Link href="/request-service" className="font-semibold text-[#f7b38e]">Request Service</Link><Link href="/request-a-quote" className="font-semibold text-[#f7b38e]">Request a Quote</Link></div></div></div><div className="border-t border-white/10"><div className="mx-auto flex max-w-[1240px] flex-col gap-3 px-5 py-5 text-xs text-white/50 sm:flex-row sm:items-center sm:justify-between lg:px-8"><span>© {new Date().getFullYear()} SPM. All rights reserved.</span><div className="flex gap-4"><Link href="/privacy">Privacy Policy</Link><Link href="/terms">Terms of Use</Link><Link href="/login">Internal access</Link></div></div></div></footer>
  </div>;
}
